doctor/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    ]

www/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^doctor/', include('doctor.urls', namespace="doctor-app")),
    url(r'^admin/', include(admin.site.urls)),
    ]

doctor/models.py
from django.db import models

class DoctorSpecs(models.Model):
    spec_code = models.CharField(max_length=10)
    spec_name = models.CharField(max_length=100)

    def __str__(self):
        return '{0}'.format(self.spec_name)

class Doctor(models.Model):
    spec = models.ForeignKey(DoctorSpecs)
    name = models.CharField(max_length=200)

    def __str__(self):
        return '{0}, {1}'.format(self.name, self.spec)
		
class Appointment(models.Model):
    app_date = models.DateTimeField()
    doctor = models.ForeignKey(Doctor)
    client_name = models.CharField(max_length=200)

    def __str__(self):
        return 'Дата и время: {0} врач: {1}'.format(self.app_date, self.doctor)

models.py
from django.db import models

DOC_SPECS = (
        ('somecode01', 'Кардиохирург'),
        ('somecode02', 'Нейрохирург'),
        ('somecode03', 'Косметолог'),
)

class Doctor(models.Model):   
    specialization = models.CharField(max_length=10, choices=DOC_SPECS)
    name = models.CharField(max_length=200)

    def __str__(self):
        return '{0}, {1}'.format(self.name, self.specialization)

class Appointment(models.Model):
    app_date = models.DateTimeField('Date and Time')
    doctor = models.ForeignKey(Doctor)
    client_name = models.CharField(max_length=200)

    def __str__(self):
        return 'Дата и время: {0}/n врач: {1}'.format(self.app_date, self.doctor)

doctor/forms.py
from django import forms
from .models import Doctor

DATE_FORMATS = [
'%Y-%m-%d %H:%M:%S',    # '2006-10-25 14:30:59'
'%Y-%m-%d %H:%M',       # '2006-10-25 14:30'
'%m/%d/%Y %H:%M:%S',    # '10/25/2006 14:30:59'
'%m/%d/%Y %H:%M',       # '10/25/2006 14:30'
'%m/%d/%y %H:%M:%S',    # '10/25/06 14:30:59'
'%m/%d/%y %H:%M',       # '10/25/06 14:30'
'%d.%m.%Y %H:%M', 		# '22.08.2015 16:52' 
'%d.%m.%Y %H:%M:%S', 	# '22.08.2015 16:52:25'
'%d.%m.%y %H:%M', 		# '22.08.15 16:52' 
'%d.%m.%y %H:%M:%S']  	# '22.08.15 16:52:25'         

class AppointmentForm(forms.Form):
    name = forms.CharField(label='ФИО', max_length=200,)
    date_time = forms.DateTimeField(label='Дата и время:', input_formats=DATE_FORMATS)
    doctor = forms.ModelChoiceField(label='Врач:',queryset=Doctor.objects.all())

doctor/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone

from .kdm_utils import CheckDatetime
from .forms import AppointmentForm
from .models import Appointment

def index(request):
    curr_date = timezone.now()
    form = AppointmentForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        name = form.cleaned_data.get('name', None)
        date_time = form.cleaned_data.get('date_time', None)
        doctor = form.cleaned_data.get('doctor', None)
		
        # creating list with dates of existing appointments
        invalid_date_list = Appointment.objects.values_list('app_date', flat=True).filter(app_date__gt=curr_date, doctor=doctor)
        if CheckDatetime(curr_date, date_time, invalid_date_list):	
            app = Appointment(app_date=date_time ,doctor=doctor, client_name=name)
            app.save()
            return HttpResponse("Запись к врачу успешно зарегистрирована!")
		
    else:
	    form = AppointmentForm()
		
    return render(request, 'doctor/index.html', { 'form': form, })

doctor/templates/doctor/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <title>Doctor form</title>
		{% load static from staticfiles %}
        <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
        <link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="{% static "bootstrap/js/bootstrap.js" %}" type="text/javascript"></script>
        {% block extrahead %}{% endblock %}
        <script type="text/javascript">
        $(function(){
        {% block jquery %}{% endblock %}
        });
        </script>
    </head>
<body>



<div class="container">
     {% block content %}{% endblock %}
</div> <!-- container -->

</body>
</html>

doctor/templates/doctor/index.html
{% extends 'doctor/base.html' %}

{% block extrahead %}
{% load static from staticfiles %}
<link href="{% static "jquery/datetimepicker/jquery.datetimepicker.css" %}" rel="stylesheet">
<script src="{% static "jquery/datetimepicker/jquery.js" %}" type="text/javascript"></script>
<script src="{% static "jquery/datetimepicker/jquery.datetimepicker.js" %}" type="text/javascript"></script>
{% endblock %}

{% block jquery %}
$("#id_date_time").datetimepicker({
  minDate:0,
  minTime:'9:00',
  maxTime:'18:00',
  dayOfWeekStart:1,
  format:'d.m.Y H:i',
  lang:'ru'
});
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <br><input type="submit" value="Submit" />
</form>
{% endblock %}